/// Flutter icons Telegram
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Telegram
///      fonts:
///       - asset: fonts/Telegram.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Telegram {
  Telegram._();

  static const _kFontFam = 'Telegram';

  static const IconData telegram = const IconData(0xe800, fontFamily: _kFontFam);
}
